# Screen size 
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FPS = 60

## Assets Paths
ASSETS_PATH = "assets"

IMAGES_PATH = f"{ASSETS_PATH}/images"
DUBU_IMAGES_PATH = f"{IMAGES_PATH}/dubu"
WATERMELON_IMAGES_PATH = f"{IMAGES_PATH}/watermelon"

SOUNDS_PATH = f"{ASSETS_PATH}/sounds"
BACKGROUND_MUSIC_PATH = f"{SOUNDS_PATH}/background"
DUBU_SOUNDS_PATH = f"{SOUNDS_PATH}/dubu"
WATERMELON_SOUNDS_PATH = f"{SOUNDS_PATH}/watermelon"